- hosts: node
  become: yes

  tasks:

  - name: Update packages
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start Docker
    service:
      name: docker
      state: started

  - name: Enable Docker
    service:
      name: docker
      enabled: yes

  - name: Stop existing container
    command: docker stop node-app
    ignore_errors: yes

  - name: Remove old container
    command: docker rm node-app
    ignore_errors: yes

  - name: Pull Docker image from Docker Hub
    command: docker pull nayan2830/node-app:latest

  - name: Run container
    command: docker run -d --restart always --name node-app -p 80:3000 nayan2830/node-app:latest
